obstacle_range: 2.0
raytrace_range: 1.5
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflation_radius: 0.50

observation_sources: laser_scan_sensor odom_sensor

laser_scan_sensor: {sensor_frame: kinect_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

odom_sensor: {sensor_frame: base_link, data_type: Odometry, topic: odom, marking:false, clearning: false}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

#obstacle_range: 2.5
#raytrace_range: 3.0
#robot_radius: 0.35
#inflation_radius: 0.50
#observation_sources: scan left_bump right_bump
#scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}
#left_bump: {data_type: PointCloud2, topic: /bump_sensor_left, marking: true, clearing: true}
#right_bump: {data_type: PointCloud2, topic: /bump_sensor_right, marking: true, clearing: true}